# Site settings
title: Bruncko, advokátní kancelář
email: advokat@bruncko.cz
description: > # this means to ignore newlines until "baseurl:"
  Advokátní kancelář Mgr. Bc. Stanislava Bruncka v Brně - jsme experti na rodinné právo, trestní právo, občanské právo, obchodní právo. Rozvod, výlučná i střídavá péče, výživné, předmanželská smlouva - se vším poradíme!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bruncko.cz" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
navigation:
- text: Úvod
  url: /
- text: Osoby v kanceláři
  url: /osoby-v-kancelari
- text: Poskytované služby
  url: /poskytovane-sluzby
- text: Publikační činnost
  url: /publikacni-cinnost
- text: Ceník
  url: /cenik
- text: Kontakt
  url: /kontakt
